# Air Pollution in East Asia

### Science of Air Pollution

#### Overview of the layers of the atmosphere/atmospheric gases

### What part of the atmosphere does air pollution affect?

### What is air pollution?

#### Overview of different types of air pollution

### Major Sources → Use as geographical overview

#### General common sources of air pollution all over the world

#### East Asian countries/communities and their prominent air pollution sources

##### Shipping

##### Traffic Emissions

### Commercial and otherwise

#### Coal

#### Urban Development

#### Manufacturing

#### Other

## The transboundary issue and its implications in regulation and politics

### Impacts

#### Human health

##### Environmental Health

#### Greenhouse gas emissions and global warming

#### Both

### Visibility

#### Environmental Justice

## Case Study: Hong Kong

### The Intersection of Air Pollution and Other Environmental Issues

#### Many environmental issues are interconnected

#### Air pollution and deforestation

### Air pollution and urbanization/industrialization

### Other Issues (To Explore)

## Goals/Other Ideas/Questions

### Ground information in geography and relevant examples

### Incorporate stories and person accounts

### slow violence → environmental justice issues

### Maybe activist or someone who has suffered the issues firsthand

#### Draw people into the empathy

#### Use stories and descriptions to describe places

#### What is the best way to section the chapter?
