# Climate Change, Climate Change Response in Myanmar


## General history of rice production and food demand in Myanmar. 

### Impact on credit policy on rice 

### Impact of infrastructure development on rice production

### Study of the constraints of rice production in Myanmar

### The effect of a command economy on food production in Myanmar 

### Overall review on demand for food in Myanmar 

### Possible implementation of SRI (systemic rice intensification) in order to increase rice yields in Myanmar

## Transition from talking about rice production

### sea-level rise

### subsidence

### coastal erosion

### coastal flooding

## Impact of climate change on rice production in Southeast Asia

### Monsoon Season effect on Ayeyarwady River Badin

### Sea Level Rise 

### Sea level rise effect on global markets/rice production


### Subsidence

Subsidence in Yangon, Myanmar

## interview segments/personal experiences of rice farmers


## Roles of the Burmese government

## Conclusion

## Reminders/Areas of Focus


