---
title: "Hydroelectric Dams"
author: "Quyen Ballagh"
date: "3/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Hydroelectric Dams in East Asia"

## Introduction

with some sort of personal or first person account? Humanize the issue, but I'm not sure if this is best to begin the chapter, or to be ncluded embedded within the science/meat of the chapter.

<span style="color: red;">
Good question. I suggest asking the Asian Collections librarian to see if there are some "narratives" or interviews with folks who have exprienced floods that you might be able to use. Also, what about classic literature? Also, here are some images you might find useful: [ENVIROLAB ASIA IMAGE GALLERY](https://scholarship.claremont.edu/envirolabasia_images/)
</span>

## Basic facts about dams in East Asia

<span style="color: red;">
I suggest you look at chapter 14, of the 2018 text, [Environmental Science of Easte Asia -- Chapter 14](https://github.com/marclos/Environmental_Science_East-Asia/raw/master/Environmental_Science--East_Asia.pdf). This might give you an idea, but also could give you some backgroud on hydrology, floods, and dams in Thailand. You might also look at this article that I wrote, although I am afraid there are a few sections that didn't get properly editted: [Narratives about Energy, Megaprojects, and the Ecology of Tropical Rivers: The Baram River Dam Project](https://scholarship.claremont.edu/cgi/viewcontent.cgi?article=1018&context=envirolabasia)
</span>


### Statistics on how many, size, scale, location etc.

<span style="color: red;">
A table would be use here -- in particular as you think about what to focus on, you might find your answer as you look at the sizes and particularities of these dams. You might look at big versus small dams and the relative costs and benefits based on the research for this table alone!  Let's see what happens.
</span>

## Function of the Dam 

### How it generates electricity/how much

### Different types of dams (multi/single use etc.) 

<span style="color: red;">
This is a critical questions -- what dams are for, makes a huge difference in their ecological impacts.  I tried to summarize this in this [textbook chapter](https://www.sciencedirect.com/science/article/pii/B9780128142660000234) but I'd like to think about more robust and interesting analysis. We can brain storm together.
</span>

## Immediate ecological impacts 

### Positive: 

#### Flood control, electricity generation, improved water quality 

### Negative: 

#### decreased water quality, flooding, sedimentation, habitat loss, deforestation, salinization etc... *note: the ecological impacts may be too many to go completely in depth into so perhaps a paragraph or subsection of each as opposed to a 7 page explanation of each 

<span style="color: red;">Yes, I think this is a good question to pursue -- I suspect as you write you will be able to narrow it down, but for now, let's see if a case study or two or three allows you to focus on one or two main topics and you can just cite others as concerns...</span>

### Anthropological impacts 

#### Supposedly positive (I.e. employment etc...)

<span style="color: red;">You might reach out to Bo Cutter and ask him about benefit-costs analyeses that seem to generate forgone conclusions, but try to quantify these!  Super interesting. </span>

#### Negative: displacement, loss of cultural sites, diseases 

##### Displacement

also provides issues of over population/crowding, sanitation issues, water quality issues etc... 

## Policy/government action/regulation  (policies that exist or propose solutions)

## Conclusion

<span style="color: red;">This is a good start -- and you have some great set of sources for a foundation. I think with some more reading you might be able to ``settle'' on some ideas, but I also think that we should meet a few more times to flesh out the outline. I don't want to get ahead of you, cause I have LOTS of ideas and it would be better if you had some sense of what you want to do first!  :-) </span>
